name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  

    - name: Build and Scan Image
      uses: ISID/build-and-scan-image@v0.2.0
      with:
        tag: boringcrawler:latest
        trivy-severity: CRITICAL
        hadolint-severity: error
        dockle-severity: FATAL
        trivy-ignore-unfixed: true
